# Generated by Django 5.2.10 on 2026-02-12 10:33

import alert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.CharField(default=alert.models.generate_alert_id, max_length=25, primary_key=True, serialize=False)),
                ('alert_status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=20)),
                ('risk_level', models.CharField(choices=[('VERY_HIGH', 'Very High'), ('HIGH', 'High'), ('MODERATE', 'Moderate')], max_length=20)),
                ('message', models.TextField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_time', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('CONFIRM_FRAUD', 'Confirm Fraud'), ('FALSE_POSITIVE', 'False Positive')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
