# Generated by Django 5.2.10 on 2026-02-09 07:16

import customer.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default=customer.models.generate_customer_id, max_length=25, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('account_id', models.CharField(default=customer.models.generate_account_id, max_length=25, primary_key=True, serialize=False)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CREDIT', 'Credit')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_status', models.CharField(choices=[('FROZEN', 'Frozen'), ('SUSPEND', 'Suspend'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Accounts',
                'db_table': 'customer_accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
