# Generated by Django 5.2.10 on 2026-03-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customeraccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
