# Generated by Django 5.2.10 on 2026-03-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customeraccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
