# Generated by Django 5.2.10 on 2026-02-09 07:16

import django.db.models.deletion
import transaction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(default=transaction.models.generate_transaction_id, max_length=25, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=10)),
                ('device_info', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit'), ('REFUND', 'Refund'), ('PAYMENT', 'Payment')], max_length=20)),
                ('transaction_channel', models.CharField(choices=[('ONLINE', 'Online'), ('ATM', 'ATM'), ('MOBILE', 'Mobile'), ('POS', 'POS')], max_length=20)),
                ('transaction_status', models.CharField(choices=[('PENDING_ANALYSIS', 'Pending Analysis'), ('FLAGGED', 'Flagged'), ('CLEARED', 'Cleared')], default='PENDING_ANALYSIS', max_length=20)),
                ('fraud_status', models.CharField(blank=True, choices=[('SUSPICIOUS', 'Suspicious'), ('SAFE', 'Safe')], default='', max_length=20)),
                ('receiver_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='customer.customeraccount')),
                ('sender_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='customer.customeraccount')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
