# Generated by Django 5.2.10 on 2026-03-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_channel',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out'), ('DEBIT', 'Debit'), ('PAYMENT', 'Payment'), ('TRANSFER', 'Transfer')], max_length=20),
        ),
    ]
